Explicit implementation of template method
- CI build broke with:
  /__w/OpenBikeSensorFirmware/OpenBikeSensorFirmware/bin/src/configServer.cpp:1159: undefined reference to `bool ObsConfig::setProperty<int>(int, String const&, int const&)'